theme = "blowfish"
baseURL = "https://sejamos1.github.io"
defaultContentLanguage = "pt-br"
enableRobotsTXT = true
summaryLength = 30
enableEmoji = true

[pagination]
  pagerSize = 10

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 100
